# Generated by Django 4.2.6 on 2023-10-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_registro_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_venta',
            name='metodo_pago',
            field=models.CharField(max_length=30),
        ),
    ]
