# Generated by Django 4.2.6 on 2023-11-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_alter_registro_venta_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_venta',
            name='metodo_pago',
        ),
    ]
